### ISSUE TITLE
Dynamic solution for authorized_keys.j2

### ISSUE THREAD

**Issue by iamdevnull** [kso512/install-check_mk-client#2]
Hi,

great role.

I would suggest to make the content of this file empty:

https://github.com/kso512/install-check_mk-client/blob/master/templates/authorized_keys.j2

Maybe a solution over variables would be better,

Best regards

**Comment by kso512** [comment]
I re-wrote this role and will deprecate this repository soon; [here](https://github.com/kso512/checkmk_agent) is the new one.

[The new role uses a blank file as suggested](https://github.com/kso512/checkmk_agent/raw/main/templates/authorized_keys.j2
).

Thank you!
